# Generated by Django 6.0.3 on 2026-03-28 19:12

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lf_name', models.CharField(max_length=50)),
                ('lf_image', models.URLField(max_length=255)),
                ('mf_name', models.CharField(max_length=50)),
                ('mf_image', models.URLField(max_length=255)),
                ('hf_name', models.CharField(max_length=50)),
                ('hf_image', models.URLField(max_length=255)),
                ('ff_name', models.CharField(max_length=50)),
                ('ff_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResonatorAscension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponAscension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_name', models.CharField(max_length=50)),
                ('green_image', models.URLField(max_length=255)),
                ('blue_name', models.CharField(max_length=50)),
                ('blue_image', models.URLField(max_length=255)),
                ('purple_name', models.CharField(max_length=50)),
                ('purple_image', models.URLField(max_length=255)),
                ('yellow_name', models.CharField(max_length=50)),
                ('yellow_image', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
                ('ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.ascension')),
                ('weapon_ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weaponascension')),
                ('weapon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
                ('minor_forte_1', models.URLField(max_length=255)),
                ('minor_forte_2', models.URLField(max_length=255)),
                ('inherent_skill_1', models.URLField(max_length=255)),
                ('inherent_skill_2', models.URLField(max_length=255)),
                ('ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.ascension')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.element')),
                ('resonator_ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.resonatorascension')),
                ('ressource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.ressource')),
                ('skill_upgrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.skillupgrade')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weapon')),
                ('weapon_ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weaponascension')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ascensions', models.ManyToManyField(to='wuwa.ascension')),
                ('characters', models.ManyToManyField(to='wuwa.character')),
                ('ressources', models.ManyToManyField(to='wuwa.ressource')),
                ('weapons', models.ManyToManyField(to='wuwa.weapon')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAscension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_lf', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_mf', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_hf', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_ff', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.ascension')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'ascension'), name='unique_ascension_user')],
            },
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('max_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('min_normal_attack_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_normal_attack_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_resonance_skill_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_resonance_skill_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_resonance_liberation_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_resonance_liberation_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_forte_circuit_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_forte_circuit_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_intro_skill_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_intro_skill_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('first_tier_trace1', models.BooleanField(default=False)),
                ('first_tier_trace2', models.BooleanField(default=False)),
                ('first_tier_trace3', models.BooleanField(default=False)),
                ('first_tier_trace4', models.BooleanField(default=False)),
                ('second_tier_trace1', models.BooleanField(default=False)),
                ('second_tier_trace2', models.BooleanField(default=False)),
                ('second_tier_trace3', models.BooleanField(default=False)),
                ('second_tier_trace4', models.BooleanField(default=False)),
                ('first_inherent_skill', models.BooleanField(default=False)),
                ('second_inherent_skill', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wuwa.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'character'), name='unique_character_user')],
            },
        ),
        migrations.CreateModel(
            name='UserResonatorAscension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('resonator_ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.resonatorascension')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'resonator_ascension'), name='unique_resonator_ascension_user')],
            },
        ),
        migrations.CreateModel(
            name='UserRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('ressource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.ressource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'ressource'), name='unique_ressource_user')],
            },
        ),
        migrations.CreateModel(
            name='UserSkillUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('skill_upgrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.skillupgrade')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'skill_upgrade'), name='unique_skill_upgrade_user')],
            },
        ),
        migrations.CreateModel(
            name='UserWeaponAscension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_green', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_blue', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_purple', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('quantity_yellow', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weapon_ascension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weaponascension')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'weapon_ascension'), name='unique_weapon_ascension_user')],
            },
        ),
    ]
