# Generated by Django 6.0.3 on 2026-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='weapon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weapontype'),
        ),
    ]
