# Generated by Django 6.0.3 on 2026-03-29 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0002_remove_character_weapon_character_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
