# Generated by Django 6.0.3 on 2026-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0003_character_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharacter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
