# Generated by Django 6.0.3 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0004_usercharacter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='release_date',
            field=models.DateField(default='2024-05-23'),
        ),
    ]
