# Generated by Django 6.0.3 on 2026-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0005_character_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='release_date',
            field=models.DateField(default='2024-05-23'),
        ),
    ]
