# Generated by Django 6.0.3 on 2026-04-03 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0006_weapon_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('max_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.weapon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'weapon'), name='unique_weapon_user')],
            },
        ),
    ]
