# Generated by Django 6.0.3 on 2026-04-03 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0007_userweapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
