# Generated by Django 6.0.3 on 2026-04-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0008_weapon_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainForte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinorForte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='main_forte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.mainforte'),
        ),
        migrations.AddField(
            model_name='character',
            name='minor_forte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wuwa.minorforte'),
        ),
    ]
