# Generated by Django 6.0.3 on 2026-04-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wuwa', '0009_mainforte_minorforte_character_main_forte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='minor_forte_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='minor_forte_2',
        ),
    ]
